on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SERVER_BASE: ${{ vars.SERVER_BASE }}
      SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
      SERVER_PATH: ${{ vars.SERVER_PATH }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: pip install poetry==1.5.1
      - run: mkdir .venv
      - run: poetry install --no-root
      - run: python write_build_cfg.py
      - run: poetry run pyinstaller --onefile --name metro_launcher --exclude-module PIL --icon assets/dva_smp_launcher.png launch.py
      - name: format filenames
        env:
          TARGET_FILENAME: ${{ fromJSON('{"windows-latest":"metro_launcher.exe","ubuntu-latest":"metro_launcher_linux","macos-latest":"metro_launcher_macos"}')[matrix.os] }}
          SHA1SUM: ${{ fromJSON('{"windows-latest":"sha1sum","ubuntu-latest":"sha1sum","macos-latest":"shasum"}')[matrix.os] }}
        run: |
          mv dist/* dist/$TARGET_FILENAME || true
          $SHA1SUM dist/$TARGET_FILENAME | cut -f1 -d ' ' > dist/$TARGET_FILENAME.sha1
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.os }}
          path: dist/*
      - name: copy file via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          target: $SERVER_PATH
